using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DB.Model
{
    [Table(name: "ALL_LICS_ARCHIVE",Schema = "ALL_LICS")]
    public class ALL_LICS_ARCHIVE
    {
        public int id { get; set; }
        public decimal? COD_UO { get; set; }
        public decimal? COD_UO_PRE { get; set; }
        public string ZAKADR { get; set; }
        public string UL { get; set; }
        public string DOM { get; set; }
        public decimal? CADR { get; set; }
        public string KW { get; set; }
        public decimal? LIC { get; set; }
        public decimal? DK { get; set; }
        public decimal? TDK { get; set; }
        public decimal? SP { get; set; }
        public decimal? SUBSNPRE { get; set; }
        public decimal? SUBSNTEK { get; set; }
        public decimal? SUBSPPRE { get; set; }
        public decimal? SUBSPTEK { get; set; }
        public DateTime? DATA { get; set; }
        public decimal? KL { get; set; }
        public decimal? SOBS { get; set; }
        public decimal? SZIL { get; set; }
        public string LGOT { get; set; }
        public decimal? NLA { get; set; }
        public decimal? SDOD { get; set; }
        public decimal? SDOE { get; set; }
        public decimal? ET { get; set; }
        public string N1 { get; set; }
        public string N2 { get; set; }
        public string N3 { get; set; }
        public string N4 { get; set; }
        public string N5 { get; set; }
        public string N6 { get; set; }
        public string N7 { get; set; }
        public string N8 { get; set; }
        public string N9 { get; set; }
        public string N10 { get; set; }
        public string N11 { get; set; }
        public string N12 { get; set; }
        public string N13 { get; set; }
        public string N14 { get; set; }
        public string N15 { get; set; }
        public decimal? SN1 { get; set; }
        public decimal? SN2 { get; set; }
        public decimal? SN3 { get; set; }
        public decimal? SN4 { get; set; }
        public decimal? SN5 { get; set; }
        public decimal? SN6 { get; set; }
        public decimal? SN7 { get; set; }
        public decimal? SN8 { get; set; }
        public decimal? SN9 { get; set; }
        public decimal? SN10 { get; set; }
        public decimal? SN11 { get; set; }
        public decimal? SN12 { get; set; }
        public decimal? SN13 { get; set; }
        public decimal? SN14 { get; set; }
        public decimal? SN15 { get; set; }
        public decimal? SR1 { get; set; }
        public decimal? SR2 { get; set; }
        public decimal? SR3 { get; set; }
        public decimal? SR4 { get; set; }
        public decimal? SR5 { get; set; }
        public decimal? SR6 { get; set; }
        public decimal? SR7 { get; set; }
        public decimal? SR8 { get; set; }
        public decimal? SR9 { get; set; }
        public decimal? SR10 { get; set; }
        public decimal? SR11 { get; set; }
        public decimal? SR12 { get; set; }
        public decimal? SR13 { get; set; }
        public decimal? SR14 { get; set; }
        public decimal? SR15 { get; set; }
        public decimal? SN1_1 { get; set; }
        public decimal? SN1_2 { get; set; }
        public decimal? SN1_3 { get; set; }
        public decimal? SN1_4 { get; set; }
        public decimal? SN1_5 { get; set; }
        public decimal? SN1_6 { get; set; }
        public decimal? SN1_7 { get; set; }
        public decimal? SN1_8 { get; set; }
        public decimal? SN1_9 { get; set; }
        public decimal? SN1_10 { get; set; }
        public decimal? SN1_11 { get; set; }
        public decimal? SN1_12 { get; set; }
        public decimal? SN1_13 { get; set; }
        public decimal? SN1_14 { get; set; }
        public decimal? SN1_15 { get; set; }
        public string ACT { get; set; }
        public string ERR { get; set; }
        public string ZAK { get; set; }
        public string TL { get; set; }
        public decimal? PENY { get; set; }
        public decimal? SE { get; set; }
        public string FIO { get; set; }
        public decimal? REZERVN1 { get; set; }
        public string DOCLG { get; set; }
        public string FIOLG { get; set; }
        public string PRIM { get; set; }
        public decimal? KVT1 { get; set; }
        public decimal? KVT2 { get; set; }
        public decimal? KVT0 { get; set; }
        public decimal? IDN { get; set; }
        public decimal? SCEL { get; set; }
        public decimal? OLDLIC { get; set; }
        public string OLDNG { get; set; }
        public string NG { get; set; }
        public decimal? SUBSNSWET { get; set; }
        public decimal? SUBSNSWETP { get; set; }
        public decimal? SUBSPSWET { get; set; }
        public decimal? SUBSPSWETP { get; set; }
        public decimal? SNSV1 { get; set; }
        public decimal? SNSV2 { get; set; }
        public decimal? SNSV3 { get; set; }
        public decimal? SNSV4 { get; set; }
        public decimal? SRSV1 { get; set; }
        public decimal? SRSV2 { get; set; }
        public decimal? SRSV3 { get; set; }
        public decimal? SRSV4 { get; set; }
        public decimal? SSSV1 { get; set; }
        public decimal? SSSV2 { get; set; }
        public decimal? SSSV3 { get; set; }
        public decimal? SSSV4 { get; set; }
        public decimal? DKE { get; set; }
        public decimal? TDKE { get; set; }
        public decimal? KME { get; set; }
        public decimal? KF { get; set; }
        public decimal? F4ECODELS { get; set; }
        public decimal? F4EKOEFTR { get; set; }
        public string F4ENUMELS { get; set; }
        public string F4EPLOMBA { get; set; }
        public decimal? KFMULTI { get; set; }
        public DateTime? DATENOPENY { get; set; }
        public decimal? SNSV5 { get; set; }
        public decimal? SSSV5 { get; set; }
        public string F4ENOEDIT { get; set; }
        public decimal? PENY_DK { get; set; }
        public decimal? PENY_SN { get; set; }
        public decimal? PENY_SR { get; set; }
        public decimal? PENY_TDK { get; set; }
        public DateTime? F4ENO2TAR { get; set; }
        public string F4EAMPPOV { get; set; }
        public decimal? ISNAB { get; set; }
        public DateTime? F4EPGBEG { get; set; }
        public string FAMIL { get; set; }
        public string IMYA { get; set; }
        public string OTCH { get; set; }
        public decimal? FKUBSXVS { get; set; }
        public decimal? FKUB1XVS { get; set; }
        public decimal? FKUB2XVS { get; set; }
        public decimal? FNORMXVS { get; set; }
        public decimal? FKUBSGVS { get; set; }
        public decimal? FKUB1GVS { get; set; }
        public decimal? FKUB2GVS { get; set; }
        public decimal? FNORMGVS { get; set; }
        public string EXT_DATA01 { get; set; }
        public string ZILIE { get; set; }
        public string NRM_OTPGVS { get; set; }
        public string NRMBOTPGVS { get; set; }
        public decimal? CODSCHOTP { get; set; }
        public decimal? CODSCHGVS { get; set; }
        public decimal? CODSCHXVS { get; set; }
        public string TARCUSTOM { get; set; }
        public decimal? ELSCE_2 { get; set; }
        public decimal? ELKV1_2 { get; set; }
        public decimal? ELKV2_2 { get; set; }
        public string F4ENOEDI_2 { get; set; }
        public decimal? FKUBSGV_2 { get; set; }
        public decimal? FKUB1GV_2 { get; set; }
        public decimal? FKUB2GV_2 { get; set; }
        public decimal? FKUBSXV_2 { get; set; }
        public decimal? FKUB1XV_2 { get; set; }
        public decimal? FKUB2XV_2 { get; set; }
        public decimal? CLOSEGVS { get; set; }
        public decimal? CLOSEXVS { get; set; }
        public decimal? FKUBSXV_3 { get; set; }
        public decimal? FKUB1XV_3 { get; set; }
        public decimal? FKUB2XV_3 { get; set; }
        public decimal? FKUBSXV_4 { get; set; }
        public decimal? FKUB1XV_4 { get; set; }
        public decimal? FKUB2XV_4 { get; set; }
        public decimal? FKUBSOT_1 { get; set; }
        public decimal? FKUB1OT_1 { get; set; }
        public decimal? FKUB2OT_1 { get; set; }
        public decimal? FKUBSOT_2 { get; set; }
        public decimal? FKUB1OT_2 { get; set; }
        public decimal? FKUB2OT_2 { get; set; }
        public decimal? FKUBSOT_3 { get; set; }
        public decimal? FKUB1OT_3 { get; set; }
        public decimal? FKUB2OT_3 { get; set; }
        public decimal? FKUBSOT_4 { get; set; }
        public decimal? FKUB1OT_4 { get; set; }
        public decimal? FKUB2OT_4 { get; set; }
        public DateTime? update_datetime { get; set; }
        public DateTime? period { get; set; }
        public int? id_all_lics { get; set; }
    }
}
