// <auto-generated />
namespace DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InstallmentaddstartandEnddate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InstallmentaddstartandEnddate));
        
        string IMigrationMetadata.Id
        {
            get { return "202308161759122_Installment add start and End date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
