// <auto-generated />
namespace DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class courtaddField08122023 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(courtaddField08122023));
        
        string IMigrationMetadata.Id
        {
            get { return "202312080908022_courtaddField-08-12-2023"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
