// <auto-generated />
namespace DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddField_Benefit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddField_Benefit));
        
        string IMigrationMetadata.Id
        {
            get { return "202404171330393_AddField_Benefit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
