// <auto-generated />
namespace DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Court_Add_EditDate_Null : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Court_Add_EditDate_Null));
        
        string IMigrationMetadata.Id
        {
            get { return "202404251727374_Court_Add_EditDate_Null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
