// <auto-generated />
namespace DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addcourtdictionary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcourtdictionary));
        
        string IMigrationMetadata.Id
        {
            get { return "202410191018304_add-court-dictionary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
