// <auto-generated />
namespace DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Court_Add_EditDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Court_Add_EditDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202404251726289_Court_Add_EditDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
