// <auto-generated />
namespace DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addcourtfieldDateSendingApplicationDebtor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcourtfieldDateSendingApplicationDebtor));
        
        string IMigrationMetadata.Id
        {
            get { return "202410071718249_add-court-field-DateSendingApplicationDebtor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
