//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.DataBase.PaymentV2Archive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counters
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Value { get; set; }
        public int PaymentId { get; set; }
        public string GUID { get; set; }
    
        public virtual Payments Payments { get; set; }
    }
}
