//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.DataBase.PaymentV2Archive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Counters = new HashSet<Counter>();
        }
    
        public int Id { get; set; }
        public System.DateTime DtCreate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentInstrument { get; set; }
        public string BankDocumentNumber { get; set; }
        public string TransactionNumberUnique { get; set; }
        public string Lic { get; set; }
        public string ELic { get; set; }
        public string Igku { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> PaymentPeriod { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public Nullable<decimal> TransferAmount { get; set; }
        public Nullable<decimal> BankCommissionAmount { get; set; }
        public Nullable<System.DateTime> PaymentDateDay { get; set; }
        public string RegisterBankName { get; set; }
        public string OrgName { get; set; }
        public string OrgOgrn { get; set; }
        public string OrgKpp { get; set; }
        public string OrgInn { get; set; }
        public string OrgCorrespondentAccount { get; set; }
        public string RequisiteName { get; set; }
        public string RequisiteCheckingAccount { get; set; }
        public string RequisiteBik { get; set; }
        public int PeriodYear { get; set; }
        public int PeriodMonth { get; set; }
        public string PaymentType { get; set; }
        public string OrgOrigamiGuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Counter> Counters { get; set; }
    }
}
