//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.DataBase.PaymentV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBFPacketFields
    {
        public int Id { get; set; }
        public int DbfPacketId { get; set; }
        public string data { get; set; }
        public int np { get; set; }
        public string nc { get; set; }
        public string ng { get; set; }
        public string lic { get; set; }
        public decimal kvpl { get; set; }
        public decimal swet { get; set; }
        public decimal peny { get; set; }
        public string wes { get; set; }
        public string err { get; set; }
        public string po { get; set; }
        public int kvt2 { get; set; }
        public int sb { get; set; }
        public string data_vv { get; set; }
        public Nullable<System.DateTime> Data_pay { get; set; }
        public int kvt1 { get; set; }
        public int month_pay { get; set; }
        public int ext_data_01 { get; set; }
        public int kvt12 { get; set; }
        public int kvt22 { get; set; }
        public decimal gvs21 { get; set; }
        public decimal xvs21 { get; set; }
        public decimal gvs22 { get; set; }
        public decimal xvs22 { get; set; }
        public int bk1__ { get; set; }
        public int bk2__ { get; set; }
        public decimal bg1__ { get; set; }
        public decimal bg2__ { get; set; }
        public decimal bx1__ { get; set; }
        public decimal bx2__ { get; set; }
        public int idusl { get; set; }
        public System.DateTime DtCreate { get; set; }
        public System.DateTime DtUpdate { get; set; }
        public int UserCreateId { get; set; }
        public int UserUpdateId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual DBFPackets DBFPackets { get; set; }
    }
}
