//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.DataBase.PaymentV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBFPackets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DBFPackets()
        {
            this.DBFPacketFields = new HashSet<DBFPacketFields>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime PaymentDateDay { get; set; }
        public string FileNameDbf { get; set; }
        public int OrgId { get; set; }
        public System.DateTime DtCreate { get; set; }
        public System.DateTime DtUpdate { get; set; }
        public int UserCreateId { get; set; }
        public int UserUpdateId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DBFPacketFields> DBFPacketFields { get; set; }
        public virtual Orgs Orgs { get; set; }
    }
}
