//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.DataBase.PaymentV2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbPaymentV2 : DbContext
    {
        public DbPaymentV2()
            : base("name=DbPaymentV2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoleClaims> AspNetRoleClaims { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AspNetUserTokens> AspNetUserTokens { get; set; }
        public virtual DbSet<Banks> Banks { get; set; }
        public virtual DbSet<Counters> Counters { get; set; }
        public virtual DbSet<DBFPacketFields> DBFPacketFields { get; set; }
        public virtual DbSet<DBFPackets> DBFPackets { get; set; }
        public virtual DbSet<F1Packets> F1Packets { get; set; }
        public virtual DbSet<Funcs> Funcs { get; set; }
        public virtual DbSet<LinkOrgBanks> LinkOrgBanks { get; set; }
        public virtual DbSet<LinkOrgFuncs> LinkOrgFuncs { get; set; }
        public virtual DbSet<LinkOrgRoles> LinkOrgRoles { get; set; }
        public virtual DbSet<OrgRequisites> OrgRequisites { get; set; }
        public virtual DbSet<Orgs> Orgs { get; set; }
        public virtual DbSet<Parsers> Parsers { get; set; }
        public virtual DbSet<ParserTypes> ParserTypes { get; set; }
        public virtual DbSet<PaymentAddresses> PaymentAddresses { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Periods> Periods { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UploadFiles> UploadFiles { get; set; }
    }
}
