//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.DataBase.PaymentV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkOrgFuncs
    {
        public int Id { get; set; }
        public int OrgId { get; set; }
        public int FuncId { get; set; }
    
        public virtual Funcs Funcs { get; set; }
        public virtual Orgs Orgs { get; set; }
    }
}
