//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.DataBase.PaymentV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parsers()
        {
            this.Banks = new HashSet<Banks>();
            this.Banks1 = new HashSet<Banks>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string FuncName { get; set; }
        public string TmplName { get; set; }
        public string Description { get; set; }
        public int ParserTypeId { get; set; }
        public System.DateTime DtCreate { get; set; }
        public System.DateTime DtUpdate { get; set; }
        public int UserCreateId { get; set; }
        public int UserUpdateId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Banks> Banks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Banks> Banks1 { get; set; }
        public virtual ParserTypes ParserTypes { get; set; }
    }
}
