//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.DataBase.PaymentV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentEntities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentEntities()
        {
            this.CounterEntities = new HashSet<CounterEntities>();
        }
    
        public int Id { get; set; }
        public System.DateTime DtCreate { get; set; }
        public System.DateTime DtUpdate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentInstrument { get; set; }
        public string BankDocumentNumber { get; set; }
        public string TransactionNumberUnique { get; set; }
        public string Lic { get; set; }
        public string ELic { get; set; }
        public string Igku { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> PaymentPeriod { get; set; }
        public decimal TransactionAmount { get; set; }
        public decimal TransferAmount { get; set; }
        public decimal BankCommissionAmount { get; set; }
        public Nullable<System.DateTime> PaymentDateDay { get; set; }
        public string Comment { get; set; }
        public int PeriodId { get; set; }
        public bool IsUploadingToOnlineSales { get; set; }
        public int PaymentType { get; set; }
        public Nullable<int> Bank_Id { get; set; }
        public Nullable<int> Org_Id { get; set; }
    
        public virtual BankEntities BankEntities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CounterEntities> CounterEntities { get; set; }
        public virtual OrgEntities OrgEntities { get; set; }
        public virtual PeriodEntities PeriodEntities { get; set; }
    }
}
