//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.DataBase.PaymentV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payments()
        {
            this.Counters = new HashSet<Counters>();
            this.PaymentAddresses = new HashSet<PaymentAddresses>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentInstrument { get; set; }
        public string BankDocumentNumber { get; set; }
        public string TransactionNumberUnique { get; set; }
        public string Lic { get; set; }
        public string ELic { get; set; }
        public string Igku { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> PaymentPeriod { get; set; }
        public decimal TransactionAmount { get; set; }
        public decimal TransferAmount { get; set; }
        public decimal BankCommissionAmount { get; set; }
        public Nullable<System.DateTime> PaymentDateDay { get; set; }
        public string Comment { get; set; }
        public int BankId { get; set; }
        public int OrgId { get; set; }
        public int OrgRequisiteId { get; set; }
        public int UploadFileId { get; set; }
        public int PeriodId { get; set; }
        public int PaymentType { get; set; }
        public System.DateTime DtCreate { get; set; }
        public System.DateTime DtUpdate { get; set; }
        public int UserCreateId { get; set; }
        public int UserUpdateId { get; set; }
        public bool IsUploadingToOnlineSales { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual Banks Banks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Counters> Counters { get; set; }
        public virtual OrgRequisites OrgRequisites { get; set; }
        public virtual Orgs Orgs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentAddresses> PaymentAddresses { get; set; }
        public virtual Periods Periods { get; set; }
        public virtual UploadFiles UploadFiles { get; set; }
    }
}
