//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.DataBase.PaymentV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodEntities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PeriodEntities()
        {
            this.PaymentEntities = new HashSet<PaymentEntities>();
        }
    
        public int Id { get; set; }
        public System.DateTime DtPeriod { get; set; }
        public System.DateTime DtCreate { get; set; }
        public Nullable<System.DateTime> DtClose { get; set; }
        public int Status { get; set; }
        public int OrgId { get; set; }
    
        public virtual OrgEntities OrgEntities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentEntities> PaymentEntities { get; set; }
    }
}
