//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.DataBase.PaymentV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadFiles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UploadFiles()
        {
            this.Payments = new HashSet<Payments>();
        }
    
        public int Id { get; set; }
        public decimal TransactionAmount { get; set; }
        public int Count { get; set; }
        public string HashFile { get; set; }
        public System.DateTime PaymentDateDay { get; set; }
        public string Message { get; set; }
        public int BankId { get; set; }
        public int OrgId { get; set; }
        public System.DateTime DtCreate { get; set; }
        public System.DateTime DtUpdate { get; set; }
        public int UserCreateId { get; set; }
        public int UserUpdateId { get; set; }
        public decimal BankCommissionAmount { get; set; }
        public int CountSkip { get; set; }
        public int CountUpdate { get; set; }
        public int OrgRequisiteId { get; set; }
        public string PathFile { get; set; }
        public decimal TransferAmount { get; set; }
        public string FinalReportData { get; set; }
        public Nullable<int> PeriodId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual Banks Banks { get; set; }
        public virtual OrgRequisites OrgRequisites { get; set; }
        public virtual Orgs Orgs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual Periods Periods { get; set; }
    }
}
